apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-devops-config
  namespace: demo-devops
  labels:
    app.kubernetes.io/name: demo-devops-python
    app.kubernetes.io/component: config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DATABASE_NAME: "db.sqlite3"
