# NOTE: In production, use Azure Key Vault with CSI driver
# or External Secrets Operator. Never commit real secrets.
apiVersion: v1
kind: Secret
metadata:
  name: demo-devops-secret
  namespace: demo-devops
  labels:
    app.kubernetes.io/name: demo-devops-python
    app.kubernetes.io/component: secret
type: Opaque
data:
  # echo -n "your-super-secret-django-key-change-me" | base64
  DJANGO_SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQtZGphbmdvLWtleS1jaGFuZ2UtbWU=
